
import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
decorations = "none"
startup_mode = "maximized"

opacity = 0.98
blur = true
option_as_alt = "Both"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"
