#+TITLE: INSTALL LOG
#+AUTHOR: Eduardo Vedes
#+STARTUP: content


* INSTALL POPOS

** Download install package (or use one in the backup disk)

** Create a Live Disk

Check how to do it [[https://support.system76.com/articles/live-disk][here]].

** Create 3 partitions:

EFI with 500MB (fat32)

Linux Swap with 8192MB (swap)

/ with remaining space (ext4 or btrfs)

** Set keyboard to US International (Intl with Dead Keys)

* CONFIGURE/CUSTOMIZE POPS

** Update and upgrade OS:

#+begin_src shell

sudo apt-get update
sudo apt-get upgrade

#+end_src

Go to Pop Shop and do the suggested updates in case any is available.

** Add Google Accounts

Add both Personal and Work Google Accounts to the Settings -> Accounts

** Configure Monitors

Go to Settings -> Displays, reorder and set the right rotation.

Set Workspaces on Primary Display Only (Settings -> Desktop -> Workspaces)

** Disable Super+P

#+begin_src shell

gsettings set org.gnome.mutter.keybindings switch-monitor "[]"

#+end_src

If you have any trouble check this [[https://askubuntu.com/questions/68463/how-to-disable-global-super-p-shortcut][link]].

** Install Google Chrome

Download *.deb package from chrome [[https://google.com/chrome][website]].

Activate sync

Signin to One Password

Add Work e-mail account

Configure Work Profile

** Install Dropbox

Use PopShop to do it.
This way we can get Multiverse and Wallpapers.
Delighter: get a fresh and new wallpaper to make you happy!  ♥

** Install Font Manager

Use PopShop to do it.

** Install fonts

Download fonts from Google Drive and use Font Manager to install them.

You can optionally create a .fonts folder on your home and copy fonts there.

Then just do the following to install them:

#+begin_src shell

fc-cache -f -v 

#+end_src

** Configure SSH Credentials

Download SSH Config and move it to ~/.ssh

- folder permissions: 700
- public files permissions: 644
- private/secret files: 600

** Install .dotfiles

Git clone .dotfiles

** Configure Network Manually (OPTIONAL)

- IP: 192.168.2.200
- Netmask: 255.255.255.0
- Gateway: 192.168.2.1
- DNS: 1.1.1.1,8.8.8.8

** Configure terminal

***  Create edo profile and set it to be the default
***  Set custom font size to 10
***  Run gogh: `bash -c "$(wget -qO- https://git.io/vQgMr)"`
***  Delete the unwanted profiles

** Configure keyboard settings

#+begin_src shell
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
gsettings set org.gnome.desktop.peripherals.keyboard delay 250
#+end_src

** Tweak keyboard shortcuts

*** Add:
**** Move to workspace above: Ctrl + Alt + Up
**** Move to workspace below: Ctrl + Alt + Down
**** Move window to upper workspace: Shift + Super + Up
**** Move window to lower workspace: Shift + Super + Down

*** Remove:

**** disable lock screen
**** disable log out
**** disable Switch to next/previous input source

*** Go to Gnome Tweaks -> Shortcuts:
**** Make Capslock an HypeKey

** Disable Super+Q to activate dock hot-keys

#+begin_src shell

gsettings set org.gnome.shell.extensions.dash-to-dock hot-keys false

#+end_src


** Configure Super+P for Launcher

Install dconf-editor from popshop.

Go to /org/gnome/shell/extensions/pop-shell/activate-launcher. 

Tweak shortcut to ['<Super>space']

Go to Settings > Desktop and assign Super action to Workspaces.

** GIT

To set your global username/email configuration:

#+begin_src shell

# Open the command line.
# Set your username

git config --global user.name "FIRST_NAME LAST_NAME"

# Set your email address

git config --global user.email "MY_NAME@example.com"

Set Vs Code as your main editor 

git config --global core.editor "code --wait"

#+end_src

To set repository-specific username/email configuration:

#+begin_src shell

# From the command line, change into the repository directory:

# Set your username

git config user.name "FIRST_NAME LAST_NAME"

# Set your email address

git config user.email "MY_NAME@example.com"

#+end_src

Verify your configuration by displaying your configuration file: `cat .git/config`

** ZSH

Install ZSH / oh-my-zsh / Powerlevel 10k:

#+begin_src shell

# install zsh
sudo apt install zsh

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# create a ln to .zshrc
ln -s ~/.dotfiles/linux/zshrc/.zshrc ~/.zshrc

#change default shell to zsh
chsh -s /bin/zsh

# install plugins

## zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

## zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# install Powerlevel 10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

#+end_src

** NODE

#+begin_src shell

# Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

# Quit terminal and open it again

nvm install --lts
nvm install --latest-npm
nvm install v14
nvm install v16
nvm alias default v16
nvm use default

# Increase the number of watchers
echo 'fs.inotify.max_user_watches=524288' | sudo tee -a /etc/sysctl.conf

# and then 
sudo sysctl -p


#+end_src


** Install YARN

#+begin_src shell

sudo npm install --global yarn

#+end_src


** DIRENV

#+begin_src shell

 sudo apt install direnv

#+end_src

Add to .zshrc (it should be there): `eval "$(direnv hook zsh)"`

** DOCKER

#+begin_src shell

sudo apt install docker docker-compose
sudo groupadd docker
sudo gpasswd -a $USER docker
newgrp docker

#+end_src

** kubectl  / minikube


#+begin_src shell

# Download latest kubectl release
curl -LO "https://dl.k8s.io/release/**$(**curl -L -s https://dl.k8s.io/release/stable.txt**)**/bin/linux/amd64/kubectl"

# Install kubectl
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Download latest minikube release
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

# Install minikube
sudo install minikube-linux-amd64 /usr/local/bin/minikube

#+end_src

** CLOJURE

#+begin_src shell

sudo apt install clojure leiningen

#+end_src

** OPENSSH

Install by doing:

#+begin_src shell

sudo apt install openssh-server
sudo systemctl enable ssh

#+end_src

* Install Software

Uninstall unwanted software, such as Open Office.

** VISUAL STUDIO CODE
Download app from site.
Turn sync settings on and login with GitHub

** Install from APT
*** VIM
*** GLANCES
*** NEOFETCH
*** TRACEROUTE

** Install from Pop Shop:

*** Gnome Tweaks
*** VS Code
*** Zulip
*** Discord
*** Franz
**** Disable Franz Todos
**** Join the Dark Force
**** Link Whatsapp Account
*** Slack
*** Flameshot
**** Add it to startup
*** Spotify
*** Telegram

** Gnome Stuff

#+begin_src shell

sudo apt install gnome-shell-extensions
sudo apt install chrome-gnome-shell

#+end_src


** Install VLC

#+begin_src shell

sudo apt install vlc
sudo apt install vlc-plugin-access-extra libbluray-bdj 

#+end_src

** INSTALL EMACS

#+begin_src shell

# remove old packages to avoid conflicts
sudo apt remote --autoremove emacs emacs-common

# add the ppa
sudo add-apt-repository ppa:kelleyk/emacs

# update system package cache
sudo apt update

# install Emacs28
sudo apt install emacs28

#+end_src

*** Install all the icons fonts. 

M-x install-all-the-icons-fonts

* KEYBOARD AND TILING

** Install Gnome Extensions:
*** OpenWeather
*** sound input device chooser
*** gTile

** Configure GTILE

    Basics: Disable Global resize presets

    Grid Sizes: 8x8,4x4,3x2

| key | dimensions | origin cell | destination cell |
|-----+------------+-------------+------------------|
| j   |        4x4 |         1:1 |              2:4 |
| ;   |        4x4 |         3:1 |              4:4 |
| k   |        3x2 |         1:1 |              2:2 |
| l   |        3x2 |         2:1 |              3:2 |
| h   |        3x2 |         1:1 |              1:2 |
| ´   |        3x2 |         3:1 |              3:2 |
| r   |        4x4 |         1:1 |              4:2 |
| v   |        4x4 |         1:3 |              4:4 |
| ]   |        4x4 |         1:1 |              4:4 |
| [   |        3x2 |         2:1 |              2:4 |
| q   |        3x2 |         1:1 |              1:1 |
| w   |        3x2 |         2:1 |              2:1 |
| e   |        3x2 |         3:1 |              3:1 |
| z   |        3x2 |         1:2 |              1:2 |
| x   |        3x2 |         2:2 |              2:2 |
| c   |        3x2 |         3:2 |              3:2 |
| u   |        4x4 |         1:1 |              2:2 |
| p   |        4x4 |         3:1 |              4:2 |
| m   |        4x4 |         1:3 |              2:4 |
| /   |        4x4 |         3:3 |              4:4 |
| i   |        3x2 |         1:1 |              2:1 |
| o   |        3x2 |         2:1 |              3:1 |
| ,   |        3x2 |         1:2 |              2:2 |
| .   |        3x2 |         2x2 |              3x2 |

* Themes

*** WhiteSur GTK Theme: https://github.com/vinceliuice/WhiteSur-gtk-theme
*** WhiteSur Icons: https://github.com/vinceliuice/WhiteSur-icon-theme
*** WhiteSur Cursors: https://www.gnome-look.org/p/1411743/


* FAQ

In case you see an error “manpath: can’t set the locale; make sure $LC_* and $LANG are correct”, one way to solve it is:

#+begin_src shell

sudo locale-gene “en_US.UTF-8”

# edit /etc/default/locale

```tsx
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

source /etc/default/locale

#+end_src



      
