start-at-login = true

after-startup-command = [
  'exec-and-forget borders active_color=0xffF1D229 width=10.0',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 10
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[[on-window-detected]]
if.app-name-regex-substring = 'system settings'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'image capture'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'calendar'
run = 'move-node-to-workspace c'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'move-node-to-workspace m'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace s'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 24
inner.vertical = 24
outer.left = 24
outer.bottom = 24
outer.top = 24
outer.right = 24

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'
alt-a = 'workspace a'
alt-c = 'workspace c'
alt-s = 'workspace s'
alt-m = 'workspace m'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0']
alt-shift-s = ['move-node-to-workspace s', 'workspace s']
alt-shift-m = ['move-node-to-workspace m', 'workspace m']
alt-shift-c = ['move-node-to-workspace c', 'workspace c']
alt-shift-a = ['move-node-to-workspace a', 'workspace a']

alt-shift-f = 'fullscreen'


alt-tab = 'workspace-back-and-forth'
ctrl-cmd-j = 'move-workspace-to-monitor --wrap-around prev'
ctrl-cmd-k = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-backslash = 'mode apps'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[mode.apps.binding]
esc = ['reload-config', 'mode main']
alt-c = 'exec-and-forget open -a /Applications/Chrome.app'
