# ~/.config/starship.toml

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false



