#!/bin/bash

BIN_NAME="$(basename "$0")"
COMMAND_NAME=$1

## COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'


sub_help () {
    echo "Usage: $BIN_NAME <command>\n"
    echo "Commands:"
    echo -e "${RED} help            This help message${NC}"
    echo "reload           Reload dotfiles"
    echo "emacs            Install Emacs 26"
    echo "spotify          Install Spotify"
    echo -e "${GREEN} all             Install using All Options${NC}"
}

sub_reload () {
    source "$HOME/.zshrc" && echo "Zsh reloaded."
}

sub_emacs () {
    sudo chmod +x install/emacs/emacs-install.bash
    bash install/emacs/emacs-install.bash
}

sub_spotify () {
    sudo chmod +x install/spotify/spotify-install.bbash
    bash install/spotify/spotify-install.bash
}

sub_all () {
    sub_emacs
    sub_reload
}

case $COMMAND_NAME in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        "sub_${COMMAND_NAME}" "$@"
        if [ $? = 127 ]; then
            echo -e "${RED}'$COMMAND_NAME' is not a known command or has errors.${NC}" >&2
            sub_help
            exit 1
        fi
        ;;
esac
